TOP  := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
ROOT = $(TOP)/../..

UNAME_P := $(shell uname -p)
ifeq ($(UNAME_P), x86_64)
    LIB_DIR := $(ROOT)/lib/ubuntu/x86_64
    LDFLAGS := -L$(ROOT)/lib/ubuntu/x86_64
else ifeq ($(UNAME_P), aarch64)
    LIB_DIR := $(ROOT)/lib/ubuntu/arm64
    LDFLAGS := -L$(ROOT)/lib/ubuntu/arm64
else
    $(warning ARCH ($(UNAME_P)) not supported)
endif
